### ISSUE TITLE
Error when reading in multiple dvw files

### ISSUE THREAD

**Issue by thomascr9** [openvolley/datavolley#2]
I am currently working with a few dvw files and I am having issues with some of them. Trying to read multiple files in at once I have used the code you suggested:
```
d <- dir("./data/2016",pattern = "dvw$", full.names = TRUE)
lx <- lapply(d, read_dv)
```
But then I get the error:
```
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  non-numeric argument to binary operator
```
Using the `tryCatch` function, I have found that about 10 out of the 31 dvw files are causing issues, but I'm not sure what would make those files any different than the rest. I have been successful using the `read_dv` function many times before so I'm not sure what the problem is now.  Any ideas?

**Comment by raymondben** [comment]
Sounds like there's something unexpected in those files that's causing the `read_dv` function to fail. Unfortunately that error message doesn't give too many hints as to what it might be (files saved with an unusual text encoding might be one possible explanation) - is it possible to send one of the files that is failing please?

**Comment by raymondben** [comment]
Some unexpected text in the file was causing the issue. Hopefully fixed as of https://github.com/raymondben/datavolley/commit/7b76c12074092e2f8647d03f420b9170c0fa9274
Reinstall the package and see how it goes. I'll leave the issue open for the time being until we're sure it's fixed.
